setwd('/home/emil/Dropbox/arbejde/cbs/phd/courses/econometrics-course/exam/test-exam-01/')

library(conflicted)
library(purrr)
library(RColorBrewer)
library(viridis)
library(scales)
library(languageserver)
library(fs)
library(qs)
library(data.table)
library(dttools) 
library(haven)
library(Hmisc)
library(GGally)
library(plotly)
library(fixest)
library(Hmisc)
library(modelsummary)
library(magrittr)
library(knitr)
library(kableExtra)
library(marginaleffects)
source('/home/emil/Dropbox/data-science/R/r-package-development/dttools/R/dtcor.R')
source('/home/emil/Dropbox/data-science/R/r-package-development/dttools/R/narv_omit.R')
source('/home/emil/Dropbox/data-science/R/r-package-development/dttools/R/dtdesc.R')
source('/home/emil/Dropbox/data-science/R/r-package-development/dttools/R/dt_ttest.R')
conflict_prefer('discard', 'purrr') 
conflict_prefer('%+%', 'dttools')
conflict_prefer('%nin%', 'dttools')
conflict_prefer('%like%', 'data.table')
conflict_prefer('transpose', 'data.table')
conflict_prefer('year', 'data.table')
conflict_prefer('filter', 'stats')
# conflict_prefer('first', 'data.table')




f1 <- read_dta('input/aerexam_cross.dta') %>% data.table()
setnames_clean(f1)
